# Generated by Django 5.1.6 on 2025-03-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_app', '0003_alter_adsatribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsatributeoptions',
            name='ads',
        ),
        migrations.AlterField(
            model_name='adsatributeoptions',
            name='ads_atribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olx_app.adsatribute'),
        ),
    ]
